# -*- mode: ruby -*-
# vi: set ft=ruby :

#
#	Ubuntu Xenial 64-bit Linux mit Docker
#
BOX_IMAGE = "ubuntu/focal64"

Vagrant.configure("2") do |config|
  HOSTNAME = "docker-2"
  config.vm.define HOSTNAME do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.network "private_network", ip: "192.168.100.11"
    subconfig.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    #end
    end
    # Shell Scripts Provision
    subconfig.vm.provision "shell", path: "scripts/vm-setup.sh"
   
  end
  # Enable agent forwarding over SSH connections
  config.ssh.forward_agent = true
end